- 21.1 Titanic Data in Seaborn `sns.load_dataset('titanic')`
- 21.2 Pivot Tables with `.groupby()`
    - E.g.: `titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()`
- 21.3 Pivot Tables with `.pivot_table()`
    - Basic: `titanic.pivot_table('survived', index='sex', columns='class', aggfunc='mean')`
    - Multi-level: `titanic.pivot_table('survived', ['sex', age], 'class')`
    - Keyword `aggfunc=col_func_dict`
    - Keyword `margins=True`
- 21.4 Example: Birthrate Data Analysis
    - Check for duplicates: `births[['year', 'month', 'day', 'gender']].duplicated().sum()`
        - No duplicated entries.
    - Check for missing data per col: `births.isna().sum()`
        - Col 'day' has 480 NA entries.
    - Check for data points per year: `births.year.value_counts(dropna=False).sort_index()`
        - Daily birthrate data for 1969-1988, monthly for 1989-2008
    - Plot pivot table: `births.pivot_table('births', index='year', columns='gender', aggfunc='sum').plot()`
    - Recipe to convert (year, month, day) to datetime and use as index:
        - `daily.index = pd.to_datetime(10000 * daily.year + 100 * daily.month + daily.day, format='%Y%m%d')`
    - Plot birthrate over day_of_week to show lower rate over the weekend:
        - `daily.pivot_table('births', index='day_of_week', columns='decade', aggfunc='mean').plot()`
        - `plt.gca().set(xticks=range(7), xticklabels=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])`
        - `plt.ylabel('mean births by day');`
    - Plot birthrate over day_of_year to show dips during big holidays:
        - `births_by_date = daily.pivot_table('births', index=[daily.index.month, daily.index.day], aggfunc='mean')`
        - `births_by_date.index = [datetime(1976, month, day) for (month, day) in births_by_date.index]`
        - `fig, ax = plt.subplots(figsize=(12, 4));    births_by_date.plot(ax=ax);`

In [49]:
# check day count per (year, month) for missing date: none found
# consider swapping year and month so that all data are shown. need to average across rows then
(filtered
 [['year', 'month']]
 .value_counts()
 .div(2)
 .sort_index()
 .to_frame()
 .unstack(0)
 .astype(int)
 .assign(average=lambda df_: df_.mean(axis=1).round(2))
)

         0                                               ...                 \
year  1969 1970 1971 1972 1973 1974 1975 1976 1977 1978  ... 1980 1981 1982
month                                                    ...
1       31   31   31   31   31   31   31   31   31   31  ...   31   31   31
2       28   28   28   29   28   28   28   29   28   28  ...   29   28   28
3       31   31   31   31   31   31   31   31   31   31  ...   31   31   31
4       30   30   30   30   30   30   30   30   30   30  ...   30   30   30
5       31   31   31   31   31   31   31   31   31   31  ...   31   31   31
6       30   30   30   30   30   30   30   30   30   30  ...   30   30   30
7       31   31   31   31   31   31   31   31   31   31  ...   31   31   31
8       31   31   31   31   31   31   31   31   31   31  ...   31   31   31
9       30   30   30   30   30   30   30   30   30   30  ...   30   30   30
10      31   31   31   31   31   31   31   31   31   31  ...   31   31   31
11      30   30   30   30   30   30   30   30   30   30  ...   30   30   30
12      31   31   31   31   31   31   31   31   31   31  ...   31   31   31

                                    average
year  1983 1984 1985 1986 1987 1988
month
1       31   31   31   31   31   31   31.00
2       28   29   28   28   28   29   28.25
3       31   31   31   31   31   31   31.00
4       30   30   30   30   30   30   30.00
5       31   31   31   31   31   31   31.00
6       30   30   30   30   30   30   30.00
7       31   31   31   31   31   31   31.00
8       31   31   31   31   31   31   31.00
9       30   30   30   30   30   30   30.00
10      31   31   31   31   31   31   31.00
11      30   30   30   30   30   30   30.00
12      31   31   31   31   31   31   31.00

[12 rows x 21 columns]